### ISSUE TITLE
Shimmer effect not working black screen is there

### ISSUE THREAD

**Issue by HiteshKanzariya07** [omtodkar/ShimmerRecyclerView#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by omtodkar** [comment]
@HiteshKanzariya07 can you provide some more insights on the issue. Logs and/or screen recording would help us.

**Comment by omtodkar** [comment]
@HiteshKanzariya07 I guess you issue is resolved at your end or you moved on, closing the issue, feel free to reopen it with more resources.
